### PR TITLE
enable source_url from fileserver

### PR DESCRIPTION
**Pull request by blbradley**
Useful in lower bandwidth or data cap situations. Promotes better security.

I didn't add all the source hashs because this may get denied. But I can find them all if I need to.

Any problems?

### CODE REVIEW

**Comment by gravyboat** [comment]
I really like this change, the breaking of backwards compatibility isn't a huge problem to me. What do you think about adding an if statement to where if the `source_hash` value isn't found it falls back to the cmd.run? Then we can preserve backwards compatibility while easily adding additional security. Did you already try this out?

**Comment by blbradley** [comment]
@gravyboat I didn't! Let me try that.

**Comment by blbradley** [comment]
I left the source_hash in each default version so they can be added as needed. Testing both cmd and archive cases. Will report soon.

**Comment by blbradley** [comment]
I updated the top description to remove statements about not finding a backwards compatible solution.

**Comment by gravyboat** [comment]
Looks great to me! Thanks @blbradley!

**Comment by blbradley** [comment]
Just finished testing! Eeeek! Good news: it works. :shipit:

**Comment by blbradley** [comment]
This PR can introduce saltstack/salt#28641 if using the fileserver on a node with 1GB memory and no swap space. It's fixed already but only in `develop`. Maybe it'll reach packages soon.

**Pull request merged**
