### PR TITLE
skip container-executor config when binary does not exist in distro

### PR DESCRIPTION
**Pull request by kitplummer**

### CODE REVIEW

**Comment by gravyboat** [comment]
Does file.managed support unless? I can't remember and the docs page is down.

**Comment by kitplummer** [comment]
Good question.  :)  I'm running it now.  Put the cart in front...

**Comment by gravyboat** [comment]
Thanks for checking!

**Comment by kitplummer** [comment]
Works!  Successfully ran against a new cluster.  Cheers.

**Comment by gravyboat** [comment]
Cool, merging this in then.

**Comment by gravyboat** [comment]
Thanks @kitplummer!

**Pull request merged**
